### ISSUE TITLE
`z.date()` generates `{}` in OpenAPI schema

### ISSUE THREAD

**Issue by falk-miracode** [risen228/nestjs-zod#99]
Using `z.date()` in a schema and producing a DTO based on that schema leads to:

- Properties of `z.date()` get serialized in the response as ISO string, like it'd be produced by `Date.prototype.toISOString()`.
- In the OpenAPI schema `z.date()` properties are defined as empty `{}`

### Zod Schema and DTO
```TypeScript
export const DateSchema = z.object({
  date: z.date()
})

export class DateDTO extends createZodDto(DateSchema) {}
```

### Controller
```TypeScript
@Controller("/date")
export class DateController {
  @Get("/now")
  @ApiOkResponse({type: DateDTO})
  getNow() {
    return DateSchema.parse({date: new Date()})
  }
}
```

### Response Body
```
{"date":"2024-05-03T08:04:35.008Z"}
```

### Open API Schema
```yaml
  /date/now:
    get:
      operationId: DateController_now
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  date: {}
                required:
                  - date
```

## What was expected

As nestjs obviously serializes properties of `Date` as ISO string (probably via `JSON.stringify()` which calls `.toJSON()` to serialize date objects), I would expect the OpenAPI schema for `z.date()` properties to be generated as `{"type": "string", "format": "date-time"}`.

```yaml
              schema:
                type: object
                properties:
                  date:
                    type: string
                    format: date-time
                required:
                  - date
```

## Further Info

- "@nestjs/common": "^9.4.3"
- "@nestjs/core": "^9.4.3"
- "@nestjs/swagger": "^7.3.1"
- "nestjs-zod": "^3.0.0"

```main.ts
// [...]
        patchNestJsSwagger()
        const document = SwaggerModule.createDocument(app, new DocumentBuilder().build())
        SwaggerModule.setup("api", app, document)
// [...]
